Fix #545 Make box name configurable in Vagrantfile
projectatomic/adb-atomic-developer-bundle pull request #569
Opened 2016-10-24 14:38 UTC by budhrg

Fix #545 

Now, one can use any box name as:
```
BOX=<box-name> vagrant up
or
export BOX=<box-name>
vagrant up
```

2016-10-25 11:06 UTC, LalatenduMohanty commented
LGTM

2016-10-25 11:07 UTC, LalatenduMohanty commented
@budhrg we need to mention this in the documentation about this.

2016-10-25 11:08 UTC, LalatenduMohanty commented
Tested to PR and it is working as expected.

2016-11-02 10:31 UTC, LalatenduMohanty requested changes
We need to mention this in the documentation.

2016-11-08 06:38 UTC, LalatenduMohanty commented
@budhrg can you please add documentation, so that we can merge this PR?

2016-11-08 11:47 UTC, budhrg commented
@LalatenduMohanty @Preeticp  Updated with documentation changes.

2016-11-09 10:31 UTC, thatdocslady reviewed
A few linguistic tweaks, looks good otherwise :)

2016-11-09 10:31 UTC, thatdocslady commented on components/rhel/misc/rhel-k8s-singlenode-setup/README.adoc
> +.  Get the latest CDK box (using Developer Subscription). You can download
remove parentheses, not needed here.

2016-11-09 10:31 UTC, thatdocslady commented on components/rhel/misc/rhel-k8s-singlenode-setup/README.adoc
> +. Add the box to Vagrant as:
as > with the following command

2016-11-09 10:31 UTC, thatdocslady commented on components/rhel/rhel-ose/README.adoc
> +. Add the box to Vagrant as:
as > with the following command

2016-11-09 10:31 UTC, thatdocslady commented on components/rhel/rhel-ose/README.adoc
> +. Add the `box-name` as an environment variable:
rephrase: "Add `box-name` as a value of the `BOX` environment variable.

2016-11-09 10:31 UTC, thatdocslady commented on docs/installing.adoc
> +# To get the virtual box box
virtual box > VirtualBox (proper noun)

2016-11-09 10:31 UTC, thatdocslady commented on docs/installing.adoc
> +Once you have downloaded the box, you can add it to `vagrant` with
`vagrant` > Vagrant (no formatting)

2016-11-09 10:31 UTC, thatdocslady commented on docs/installing.adoc
> +# Add the box to vagrant
Vagrant

2016-11-09 10:31 UTC, thatdocslady commented on docs/installing.adoc
> +After adding box, set an environment variable as:
After adding the box, set the box name as the value of the BOX environment variable.

2016-11-09 11:09 UTC, Preeticp commented on components/rhel/misc/rhel-k8s-singlenode-setup/README.adoc
> ++
Should we add a line here saying, 'you can customize the box-name as per your requirements'

2016-11-09 11:11 UTC, Preeticp commented on docs/installing.adoc
> +----
Add a line saying, this allows you to customize the box name as per your requirements.

2016-11-09 11:13 UTC, Preeticp commented
@budhrg, Installation doc for the ADB doc fix is good, but I wonder why these steps are not relevant in the ADB Vagranfile Readmes.  What I understand is when we download ADB via Vagrantfiles these steps are not required as user can customize the box name in that case, but when he manually downloads a vagrant box these steps are required, is that correct? If it is correct, would it be a good idea to mention in the Vagrantfiles Initiated Download section that - when you use these ADB Vagrantfiles, you can customize the name of the box as per your requirements. This point was not very obvious earlier.

2016-11-09 12:08 UTC, budhrg commented on components/rhel/misc/rhel-k8s-singlenode-setup/README.adoc
> ++
I  think it is not require here.

2016-11-15 12:02 UTC, thatdocslady commented
+1 LGTM

2016-11-15 12:57 UTC, budhrg commented
@LalatenduMohanty Pushed changes for centos based Vagrantfiles too as doc includes for ADB too.

2016-11-15 13:14 UTC, Preeticp commented
LGTM

2016-11-17 10:39 UTC, LalatenduMohanty approved these changes

2016-11-17 10:39 UTC, merged