Fix #566 Updated Proxy section by pointing it to VSM docs.
projectatomic/adb-atomic-developer-bundle pull request #572
Opened 2016-10-26 12:56 UTC by Preeticp

As part of this issue, reworded the Proxy setup section in vagrant-service-manager readme and linked the ADB installation step to the vsm readme.
Also separated the start ADB substep from Step 5 and made it into Step 7 as it seemed logically the correct order of steps.

2016-10-26 13:01 UTC, Preeticp commented
@budhrg, @LalatenduMohanty request your review.

2016-10-26 13:04 UTC, brgnepal commented on docs/installing.adoc
> +This will download ADB and set it up to work with the provider of
Why download ADB again here? It is done in step 5 right?

2016-10-27 10:22 UTC, praveenkumar commented
LGTM.

2016-10-27 18:12 UTC, LalatenduMohanty commented on docs/installing.adoc
Steps to set proxy server information is a very important piece of ADB user experience. So I think this section should should contain VSM config options and we should not redirect users for the information. @Preeticp @budhrg @praveenkumar comments?

2016-10-28 05:36 UTC, Preeticp commented on docs/installing.adoc
Makes sense @LalatenduMohanty!

2016-10-28 11:31 UTC, LalatenduMohanty commented on docs/installing.adoc
> +In an unauthenticated proxy environment, the `http_proxy_user` and `http_proxy_password` configurations can be omitted.
@Preeticp I am not able to understand purpose of `In an unauthenticated proxy environment, the `http_proxy_user` and `http_proxy_password` configurations can be omitted. ` Can you please add more context.

2016-10-28 14:55 UTC, brgnepal commented on docs/installing.adoc
> +In an unauthenticated proxy environment, the `http_proxy_user` and `http_proxy_password` configurations can be omitted.
@LalatenduMohanty , this refers to username/password less proxy server url.

2016-11-02 10:17 UTC, LalatenduMohanty commented
@Preeticp Looks like there is a bug in VSM  and these settings does not work .Lets wait for PR https://github.com/projectatomic/vagrant-service-manager/pull/435 to merge and then we can rework and merge this PR.

2016-11-17 10:37 UTC, LalatenduMohanty commented
@Preeticp https://github.com/projectatomic/vagrant-service-manager/pull/435 is fixed now. Can you please update the PR as per the new code?

2016-11-21 11:05 UTC, LalatenduMohanty requested changes

2016-11-21 11:05 UTC, LalatenduMohanty commented on docs/installing.adoc
> +>>>>>>> b60c866... Fix #566 Updated Proxy section with the relevant steps from VSM.
@Preeticp Looks like the rebase did not work properly for you. Please clean up the PR.

2016-11-21 11:05 UTC, LalatenduMohanty commented on docs/installing.adoc
> +<<<<<<< HEAD
Same comment as above.

2016-11-21 11:05 UTC, LalatenduMohanty commented on docs/installing.adoc
> +>>>>>>> b60c866... Fix #566 Updated Proxy section with the relevant steps from VSM.
Same review comment as above.

2016-11-21 11:05 UTC, LalatenduMohanty commented on docs/installing.adoc
> +>>>>>>> b60c866... Fix #566 Updated Proxy section with the relevant steps from VSM.
Same comment as above.

2016-11-21 12:44 UTC, LalatenduMohanty approved these changes

2016-11-21 12:44 UTC, LalatenduMohanty commented
LGTM

2016-11-21 12:45 UTC, merged