Added docs on staging app with OpenShift registry
projectatomic/adb-atomic-developer-bundle pull request #574
Opened 2016-11-04 13:18 UTC by thatdocslady

Fixes #547 

This topic describes the use-case of deploying an application locally by hooking into the OpenShift Docker registry. This step can be performed after testing the app and before pushing to production. 

Created a separate topic based on a modular approach to the docs and to allow for future porting/reusing the content as needed based on scenarios.

2016-11-04 13:19 UTC, thatdocslady commented
@LalatenduMohanty @praveenkumar @Preeticp please review and comment, feel free to tag other stakeholders as needed :)

2016-11-08 06:03 UTC, praveenkumar commented on docs/staging.adoc
> +from the `service-manager env` command.
vagrant service-manager env command.

2016-11-08 06:19 UTC, Preeticp commented on docs/staging.adoc
> +
Would it be a good idea to add ‘sample-project’ is the name of the ADB default project, in the assumed parameters section?

2016-11-08 06:20 UTC, praveenkumar commented on docs/staging.adoc
> +
That's also a good idea. :+1:

2016-11-08 06:25 UTC, Preeticp commented on docs/staging.adoc
> ++
This is part of the code block which is returned when user runs the `$ vagrant service-manager env openshift` command.

2016-11-09 10:07 UTC, thatdocslady commented
@LalatenduMohanty @praveenkumar @Preeticp I implemented your feedback, thanks! Please ack/merge if ok.

2016-11-09 10:11 UTC, Preeticp commented
LGTM. @thatdocslady really liked the idea of the paragraph on the assumed parameters, makes it easy for the user to understand.

2016-11-09 13:17 UTC, praveenkumar commented
LGTM :+1:

2016-11-09 21:19 UTC, LalatenduMohanty requested changes

2016-11-09 21:19 UTC, LalatenduMohanty commented on docs/staging.adoc
> +
@thatdocslady This point about `build config` is not clear to me.  What are we trying to communicate here?

2016-11-10 07:42 UTC, praveenkumar commented on docs/staging.adoc
> +
This scenario is intended to illustrate how to test an application that isn’t already pushed to a public instance of OpenShift and that is not accessible by OpenShift build config. ==> This scenario is intended to illustrate how to test an application docker image to OpenShift platform (running in ADB box) which is available on your host before push it to a public instance of OpenShift.

@thatdocslady @LalatenduMohanty Does that make sense?

2016-11-10 09:07 UTC, thatdocslady commented on docs/staging.adoc
> +
@praveenkumar yes that's more clear, @LalatenduMohanty this text was something I took from the developer blog that you linked originally, will fix and update the PR.

2016-11-10 09:39 UTC, LalatenduMohanty commented
LGTM

2016-11-10 09:39 UTC, merged