Fix #570 Consistent format for setting Vagrantfile configurations
projectatomic/adb-atomic-developer-bundle pull request #586
Opened 2016-11-15 13:18 UTC by budhrg

Fix #570 

@praveenkumar ,  JFYI, I have removed the empty assignment of PROXY* constants now. 
It seems to be working without that too. Please check the Vagrantfiles.

2016-11-17 10:06 UTC, praveenkumar commented on components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile
> +
What if we only have proxy server without authentication so how this will work out. does it set `PROXY_USERNAME` and `PROXY_PASSWORD` as `''`?

2016-11-17 10:15 UTC, LalatenduMohanty requested changes

2016-11-17 10:15 UTC, LalatenduMohanty commented on components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile
> +    config.registration.proxyPassword = PROXY_PASSWORD = ENV['PROXY_PASSWORD']
This assumption is not correct. You can have a proxy environment which do not have user name and password.

2016-11-17 10:33 UTC, budhrg commented on components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile
> +
Yes @praveenkumar , but what is expected in that case? 
Empty or null ?

2016-11-17 10:40 UTC, praveenkumar commented on components/rhel/misc/rhel-k8s-singlenode-setup/Vagrantfile
> +
@budhrg it suppose to be empty because otherwise it is undefined. Also make sure you did testing for this change.

2016-11-21 10:38 UTC, LalatenduMohanty approved these changes

2016-11-21 10:38 UTC, LalatenduMohanty commented
LGTM

2016-11-21 10:38 UTC, merged