Fixed section IDs and relative links to other docs
projectatomic/adb-atomic-developer-bundle pull request #594
Opened 2016-11-21 12:54 UTC by thatdocslady

Fixes #553 

This PR addresses the following concerns raised in the issue:

- Fix section/topic IDs after asciidoc conversion (many of them were long and clumsy)
- Fix links to other docs in the repo to be relative (instead of hard-coded) to allow them to parse into HTML links when we publish docs later
- Minimize links to other repos (only a handful of them are currently used and only when absolutely necessary)

Reviews welcome!

2016-11-21 20:17 UTC, LalatenduMohanty requested changes

2016-11-21 20:17 UTC, LalatenduMohanty commented on docs/installing.adoc
> +<<<<<<< a7f6568029db13e9f431b881a8ba11942dd28eb4
@thatdocslady Please fix this. I think this is a byproduct of rebase.

2016-11-21 20:17 UTC, LalatenduMohanty commented on docs/installing.adoc
>  == Step 6. (Optional) Set up ADB behind an HTTP proxy
`setup-http-proxy` looks incorrect. The section represents `how to setup ADB behind a proxy setup`

2016-11-22 13:01 UTC, thatdocslady commented
@LalatenduMohanty fixed the sections per your feedback, thanks! @hferentschik @Preeticp can you also please review? Cheers :)

2016-11-23 18:55 UTC, LalatenduMohanty approved these changes

2016-11-23 18:56 UTC, LalatenduMohanty commented
@Preeticp waiting for your review. Thanks.

2016-11-24 04:28 UTC, Preeticp commented
There is just this one substep in step 5, in the Installation guide, being discussed, apart from that, the rest LGTM.

2016-11-24 09:29 UTC, thatdocslady commented
@Preeticp fixed step 5 in the install doc per our discussion.

2016-11-24 09:40 UTC, Preeticp commented
LGTM @thatdocslady, @LalatenduMohanty

2016-11-24 09:41 UTC, merged